### ISSUE TITLE
The value maybe int or None, not string and cause error 

### ISSUE THREAD

**Issue by truclk** [nops-io/kafka_tools#1]
https://github.com/nops-io/kafka_tools/blob/27194d5bdf1e1c6dec920ee8768fd82cdf9eb6cc/kafka_tools/__init__.py#L81

**Comment by nzagorsky** [comment]
Addressed that here: https://github.com/nops-io/kafka_tools/commit/5ac1bd131a4b0b4ceb70ff7a5cbf00c8dfbfffa3
